### ISSUE TITLE
Extension not bringing selected VS Code into Snappify

### ISSUE THREAD

**Issue by bdenham** [snappify-io/vscode-extension#2]
The extension opens Snappify in a new browser window, but does not create a new snap project with the code inserted. It only opens Snappify to the projects page, where my latest snap is shown. 

Things that might be different about my setup:
- I’ve created a local “web app” with Chrome so I can access the web version of Snappify from the Dock of my Intel-based 2020 iMac. 
- I’ve also installed and use the desktop version of Snappify. 

That’s all I can think of that may be different from other users that don’t have this problem. So hopefully there’s a quick fix you can suggest on my side. Thanks!

**Comment by dsumer** [comment]
Hey! Hm, that sounds strange.

When you click on "Open in Snappify", a modal opens up and asks you if you want to Open the Link or Copy it. Can you please Copy it and paste the result in here so I can take a look what could be the problem there?

![CleanShot 2023-11-23 at 08 37 13@2x](https://github.com/snappify-io/vscode-extension/assets/4418879/f321511c-1aca-4c35-a4eb-4ec2640d8170)

**Comment by bdenham** [comment]
Hey @dsumer, sorry this took me so long:

As copied:

https://snappify.com/new?p=0&f=Button.tsx&l=tsx&c=export%20interface%20ButtonProps%0A%20%20extends%20Omit%3CHTMLAttributes%3CHTMLButtonElement%3E%2C%20'size'%20%7C%20'icon'%3E%20%7B%0A%20%20variant%3F%3A%20'primary'%20%7C%20'secondary'%20%7C%20'tertiary'%3B%0A%20%20size%3F%3A%20'medium'%20%7C%20'large'%3B%0A%20%20children%3F%3A%20ComponentChildren%3B%0A%20%20icon%3F%3A%20VNode%3CHTMLAttributes%3CSVGSVGElement%3E%3E%3B%0A%20%20disabled%3F%3A%20boolean%3B%0A%20%20active%3F%3A%20boolean%3B%0A%20%20activeChildren%3F%3A%20ComponentChildren%3B%0A%20%20activeIcon%3F%3A%20VNode%3CHTMLAttributes%3CSVGSVGElement%3E%3E%3B%0A%7D

Decoded:

```url
https://snappify.com/new?p=0&f=Button.tsx&l=tsx&c=export interface ButtonProps
  extends Omit<HTMLAttributes<HTMLButtonElement>, 'size' | 'icon'> {
  variant?: 'primary' | 'secondary' | 'tertiary';
  size?: 'medium' | 'large';
  children?: ComponentChildren;
  icon?: VNode<HTMLAttributes<SVGSVGElement>>;
  disabled?: boolean;
  active?: boolean;
  activeChildren?: ComponentChildren;
  activeIcon?: VNode<HTMLAttributes<SVGSVGElement>>;
}
```

**Comment by bdenham** [comment]
@dsumer Any updates on this?

**Comment by dsumer** [comment]
Hey @bdenham, I've just pushed a potential fix for the issue, can you please check if it's now working for you?

If not, please send me any errors visible in your Browser Console so I can see what's the issue in your case :D

**Comment by bdenham** [comment]
Success! Works beautifully now. Thanks so much for the fix!
